#!/usr/bin/env bash
# Bash script that transfers file from client(ALX) to a server

# Function to display usage
display_usage() {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Checks the number of arguments
if [ "$#" -lt 4 ]; then
    display_usage
    exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Construct the scp command with necessary options
	scp -o "StrictHostKeyChecking=no -i $SSH_KEY_PATH $FILE_PATH $USERNAME@$SERVER_IP":~/;
