#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
# Exception of TCP ports 22, 443, 80

# command to install ufw
sudo apt install ufw
# Denies incoming connections
sudo ufw default deny incoming
# Allows port 22, 443, 80
sudo ufw allow 22
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# Enables ufw
sudo ufw enable
# check ufw status
sudo ufw status verbose
